import Link from "next/link";
import {
  isPublicPrototypePrincipal,
  principalHasRole,
  principalHasPermission,
  requirePermission
} from "@/lib/authorization";
import { knowledgeProviderStatus } from "@/lib/knowledge/config";
import { getGrantKnowledgeOverview } from "@/lib/knowledge/search";
import { KnowledgeSearchPanel } from "./knowledge-search-panel";
import { MetricHelp, MetricLabel } from "../metric-help";

function numberText(value: number | string | null | undefined) {
  const parsed = Number(value ?? 0);
  return Number.isFinite(parsed) ? parsed.toLocaleString("en-US") : "0";
}

function dateText(value: string | null) {
  if (!value) {
    return "-";
  }

  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime())
    ? "-"
    : parsed.toLocaleString("en-US", {
        month: "short",
        day: "numeric",
        hour: "numeric",
        minute: "2-digit"
      });
}

function embeddingBacklogText(count: number) {
  return count === 0 ? "Caught up" : `${numberText(count)} remaining`;
}

function lastEmbeddingRunText({
  action,
  createdAt,
  embedded,
  skipped
}: {
  action: string | null;
  createdAt: string | null;
  embedded: number | null;
  skipped: number | null;
}) {
  if (!createdAt) {
    return "No embedding run recorded yet.";
  }

  const source = action === "knowledge.embed.scheduled"
    ? "scheduled"
    : action === "knowledge.embed.scheduled.failed"
      ? "scheduled failed"
      : "manual";
  const embeddedText = embedded === null ? "" : `; ${numberText(embedded)} embedded`;
  const skippedText = skipped ? `; ${numberText(skipped)} skipped` : "";

  return `Last ${source} run: ${dateText(createdAt)}${embeddedText}${skippedText}`;
}

const knowledgeHelp = {
  documents:
    "Count of grant_knowledge_documents rows generated by the knowledge index. These are searchable chunks built from canonical applications and their linked source records.",
  applications:
    "Distinct canonical grant_applications represented in grant_knowledge_documents. This shows how much of the reconciled corpus is searchable.",
  latestIndex:
    "Most recent indexed_at timestamp in grant_knowledge_documents. If source data was synced/reconciled after this time, rebuild the index.",
  embeddings:
    "Count of knowledge documents with a current embedding for the configured embedding model, dimensions, and content hash.",
  embeddingBacklog:
    "Knowledge documents that still need a current semantic embedding. The scheduled embedding worker periodically processes this backlog.",
  aiAnswers:
    "Configuration status for grounded answer composition. It reflects whether the AI answer provider key is available, not a count of answers.",
  indexedSource:
    "Knowledge documents grouped by source_kind or document_kind. These counts explain what evidence types are represented in retrieval."
};

export default async function GrantKnowledgePage() {
  const principal = await requirePermission("knowledge:search", { allowPublicPrototypeRead: true });
  const [overview, providerStatus] = await Promise.all([
    getGrantKnowledgeOverview(),
    Promise.resolve(knowledgeProviderStatus())
  ]);
  const canComposeAi =
    !isPublicPrototypePrincipal(principal) &&
    (await principalHasPermission(principal.id, "knowledge:compose"));
  const canIndex =
    !isPublicPrototypePrincipal(principal) &&
    (await principalHasRole(principal.id, "admin"));
  const canUseSemantic =
    !isPublicPrototypePrincipal(principal) &&
    (await principalHasPermission(principal.id, "knowledge:semantic"));

  return (
    <main className="admin-shell">
      <section className="admin-header">
        <div>
          <p className="eyebrow">Decision support</p>
          <h1>Grant knowledge retrieval</h1>
          <p className="lead">
            {isPublicPrototypePrincipal(principal) ? (
              <>
                Public read-only prototype view. <Link className="table-link" href="/sign-in">Sign in</Link> for dashboard operations.
              </>
            ) : (
              <>
                Signed in as <span className="code">{principal.email}</span>.
              </>
            )}
          </p>
        </div>
      </section>

      <KnowledgeSearchPanel
        canComposeAi={canComposeAi}
        canIndex={canIndex}
        canUseSemantic={canUseSemantic}
        initialAiConfigured={providerStatus.aiConfigured}
        initialSemanticEnabled={providerStatus.semanticSearchEnabled}
      />

      <details className="operations-disclosure knowledge-operations">
        <summary>
          <span>Corpus and index status</span>
          <small>Index, embedding, provider, and source coverage</small>
        </summary>
        <div className="operations-disclosure-body">
          <section className="metric-grid" aria-label="Grant knowledge summary">
            <article className="metric-card">
              <MetricLabel body={knowledgeHelp.documents} label="Knowledge documents" text="Knowledge documents" />
              <strong>{numberText(overview.documentCount)}</strong>
            </article>
            <article className="metric-card">
              <MetricLabel body={knowledgeHelp.applications} label="Applications covered" text="Applications covered" />
              <strong>{numberText(overview.applicationCount)}</strong>
            </article>
            <article className="metric-card">
              <MetricLabel body={knowledgeHelp.latestIndex} label="Latest index" text="Latest index" />
              <strong>{dateText(overview.latestIndexedAt)}</strong>
            </article>
            <article className="metric-card">
              <MetricLabel body={knowledgeHelp.embeddings} label="Embeddings" text="Embeddings" />
              <strong>{numberText(overview.embeddingCount)}</strong>
              <span className="metric-note">
                {providerStatus.embeddingModel} · {numberText(overview.documentCount)} total
              </span>
            </article>
            <article className="metric-card">
              <MetricLabel body={knowledgeHelp.embeddingBacklog} label="Embedding backlog" text="Embedding backlog" />
              <strong>{embeddingBacklogText(overview.embeddingBacklogCount)}</strong>
              <span className="metric-note">
                {lastEmbeddingRunText({
                  action: overview.lastEmbeddingRunAction,
                  createdAt: overview.lastEmbeddingRunAt,
                  embedded: overview.lastEmbeddingRunDocumentsEmbedded,
                  skipped: overview.lastEmbeddingRunDocumentsSkipped
                })}
              </span>
            </article>
            <article className="metric-card">
              <MetricLabel body={knowledgeHelp.aiAnswers} label="AI answers" text="AI answers" />
              <strong>{providerStatus.aiConfigured ? "Configured" : "Not set"}</strong>
              <span className="metric-note">{providerStatus.aiModel}</span>
            </article>
          </section>

          <section className="panel">
            <div className="section-heading">
              <div className="heading-with-help">
                <h2>Indexed sources</h2>
                <MetricHelp body={knowledgeHelp.indexedSource} label="Indexed source counts" />
              </div>
            </div>
            <div className="source-counts compact-source-counts">
              {overview.sourceKinds.length ? (
                overview.sourceKinds.map((sourceKind) => (
                  <div className="source-count" key={sourceKind.sourceKind}>
                    <span>
                      {sourceKind.sourceKind}
                      <MetricHelp align="left" body={knowledgeHelp.indexedSource} label={`${sourceKind.sourceKind} knowledge documents`} />
                    </span>
                    <strong>{numberText(sourceKind.documentCount)}</strong>
                  </div>
                ))
              ) : (
                <p>No knowledge documents indexed yet.</p>
              )}
            </div>
          </section>
        </div>
      </details>
    </main>
  );
}
